---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache
    tags: always
    dnf: 
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base

- hosts: test_server
  become: true
  roles:
    - test_server

- hosts: workstations
  become: true
  roles: 
    - workstations
