---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    
- hosts: test_server
  become: true
  tasks:

  - name: install apache, php, mariadb, samba
    tags: apache,rhel,httpd,db,mariadb,samba
    dnf: 
      name: 
        - php
        - mariadb
        - samba
        - httpd
      state: latest

  - name: latest index.html file is present
    tags: apache,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: httpd is started
    service: 
      name: httpd
      state: started   

- hosts: workstations 
  become: true
  tasks: 

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root  
